language: julia

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build()'
        - julia --project --check-bounds=yes -e 'Pkg.add("Documenter")'
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.instantiate()'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip
